### ISSUE TITLE
Finally, a VSIX for 2017

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1442]
I would like you guys to try this for me, please.

https://1drv.ms/f/s!Aq5BEHo6GlC-t7Nq2MfoysgSaZknJA

Be sure and give me feedback, even if it works - especially if it works!

**Comment by darenm** [comment]
I'll take a look.

**Comment by darenm** [comment]
The template installed and I was able to create, compile and run an instance of all three templates in VS 2017 Enterprise V 15.1 (26403.3) running on W10 15063.14

**Comment by JerryNixon** [comment]
I would like someone try installing it in VS 2015 as a test, too

**Comment by darenm** [comment]
I don't do retro 😆

**Comment by michaelhutchful** [comment]
Dear Jerry,

I will give it a shot over the weekend vs2017, is there a timeline for release?

Regards Michael Hutchful

Sent from Mail for Windows 10

**Comment by brianobr** [comment]
**VS2015**
Clean install of VS2015 14.0.25431.01 with default installation (+ Universal Tools & SDK) onW10 14393.1066
Failed:
   VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
I opened the vsixmanifest file in the vsix and added 
`<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0]" />` to the Installation section & installed happily.

However, on trying to create a new blank Template10 project I got the error

> Unable to copy the file 'Microsoft.NETCore.UniversalWindowsPlatform' from the project template to the project. Cannot find file "C:\Users\brian\AppData\Local\Temp\xkps32sd.yuf\Temp\Microsoft.NETCore.UniversalWindowsPlatform".

**VS2017**
Ditto for Daren's results

**Comment by juanluelguerre** [comment]
Hi Jerry,

**VS2017**: It's works perfectly for VS2017 Enterprise Edición, v15.1(26403.3).
**VS2015**: It's not work for VS2015 Enterprise 2015 v14.25420.01 Update 3. I've change vsixmanifest as @brianobr said, and after the installation successfully, I've got the same error for: Blank, Minimal and Hammburger templates.

Thanks for your efforts
Regards
Juanlu

**Comment by marcusrunge** [comment]
No issues installing on Visual Studio 2017 Version 15.1 (26403.3)
I found the following issues after installing and Setting up a **Hamburger** App:

1. NuGet Update to Newtonsoft.Json v10.0.2 Fails (9.0.1 is ok)
2. Warning: Bootstrapper.EnableAutoRestoreAfterTerminated is outdated, "use AutoRestoreAfterTerminated"
3. Warning: Minimal_TemporaryKey.pfx not found, but a Hamburger_TemporaryKey.pfx Shows up. In package app manifest I have to generate a new certificate.
4. Publisher in Package.appxmanifest Shows: CN=daren

**Comment by marcusrunge** [comment]
Another one:
If I try to change colors in Shell.xaml, there is no effect. The hamburger menu pane remains grey and the Buttons Color unchanged

**Comment by openstud** [comment]
Thank you!

https://goo.gl/images/CBpHzc

**Comment by dg2k** [comment]
@JerryNixon 
Not sure if I'm late to the VSIX test-drive invite (was off on vacation) but here is my feedback;

First impressions:
The templates compiled and run without a problem (although there were a couple of compilation errors which were later cleared after updating UniversalWindowsPlatform to 5.3.1 and Xaml.Behaviors.Uwp.Managed to 2.0.0).

Test environment:
VS 2017 Pro 15.1 (26403.7) running on W10 Enterprise 14393

**Comment by Quico20** [comment]
I've tested Template 10, for the first time at VS 2015 and VS 2017 both enterprise edition, and so far works well! I'll be reporting issues while I develop my app, I'm kinda new at Template 10.

**Comment by NEKIT-Boss** [comment]
All three templates are working perfectly!
 
VS Version:
![image](https://cloud.githubusercontent.com/assets/16296644/25255411/15739946-2633-11e7-8dad-848fa7a81065.png)

**Comment by harvinders** [comment]
Works on visual studio 2017 community 15.0 too (on Creator Update).

**Comment by QuentinSc** [comment]
Everything is ok17 Community 15063

**Comment by DennisTycho** [comment]
Hi,
What are the prerequisites for installing this extension?

I keep getting an error when trying to create any of the 3 project types. If I look in the activity log for VS, the only error that I get is:

System.Runtime.InteropServices.COMException (0x80004005): The project requires a platform SDK (10.0.14393.0) that is not installed. Please visit the following link for more information: https://go.microsoft.com/fwlink/?linkid=824810&#x000D;&#x000A;   at Microsoft.VisualStudio.ProjectFlavoring.Load.VetoProjectLoadManager.CheckCanLoad()&#x000D;&#x000A;   at Microsoft.VisualStudio.ProjectFlavoring.ProjectFlavor.OnAggregationComplete()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.Microsoft.VisualStudio.Shell.Flavor.IVsAggregatableProjectCorrected.OnAggregationComplete()&#x000D;&#x000A;   at EnvDTE.SolutionClass.AddFromTemplate(String FileName, String Destination, String ProjectName, Boolean Exclusive)&#x000D;&#x000A;   at Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]&amp; ContextParams, Object[]&amp; CustomParams, wizardResult&amp; retval)&#x000D;&#x000A;   at Microsoft.VisualStudio.Dialogs.CreateProjectResult.ReturnOrThrow()&#x000D;&#x000A;   at Microsoft.VisualStudio.Dialogs.SVsDialogService.InvokeDialog(VSNEWPROJECTDLGINFO dlgInfo, String&amp; bstrLocation)&#x000D;&#x000A;   at Microsoft.VisualStudio.PlatformUI.NewProjectViewModel.OnClickedCommandExecuted(Object parameter)

Even though I have Windows Software Development Kit - Windows 10.0.14393.795 installed, besides 
several other SDK's


VS 2017 (Version 15.1 (26403.7))
Win 10 Enterprise 15063.138

Best regards!
Dennis

EDIT: (SOLVED)
After having downloaded all code, and opening the Template10 solution, i was able to get the missing SDK (10.0.14393.0). After it all worked  ;-)
Conclusion: PreReq: Windows SDK 10.0.14393.0.

**Comment by syaifulnizamyahya** [comment]
Works on my Visual Studio 2017. No problem at all.

**Comment by chain-xvi** [comment]
![image](https://cloud.githubusercontent.com/assets/27561160/25579555/ddf5f9e6-2e70-11e7-98b7-4e87ddd71d5a.png)

**Comment by DennisTycho** [comment]
@iamanas20 
I got the same error, but when looking in the activityLog for VS, I found that it was because I did not have the right WIndows SDK installed. You need the Windows SDK 10.0.14393.0. I got it by downloading the Template 10 sourcecode from github. When building this, I was prompted to install the needed version.

**Comment by chain-xvi** [comment]
@DennisTycho How exactly I can do that!

**Comment by DennisTycho** [comment]
In the Code tab, you can choose to download in the upper right corner.

Perhaps if you could get the specific version of the SDK in any other way, that would be preferable. But i do not know how.

**Comment by chain-xvi** [comment]
@DennisTycho It worked, I have installed the Windows SDK 10.0.14393.0 for VS2017 via the Visual Studio installer!

**Comment by kaki104** [comment]
It is installed normally in the release version of Visual Studio Enterprise 2017 version 15.1 (26403.7) and runs without problems when the project is created and executed.
